services:
  postgres:
    container_name: prescription_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=prescriptiondb
      - POSTGRES_PASSWORD=springpassword
      - POSTGRES_USER=springuser
    ports:
      - 49154:5432
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - 5672