version: '3.8'

services:
  postgres:
    container_name: best_test_db
    image: postgres:latest
    environment:
      POSTGRES_DB: best_test_db
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpassword
    ports:
      - "58444:5432"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"